# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bibliouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliouser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='bibliouser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='BiblioUser',
        ),
    ]
