# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=40),
        ),
    ]
