# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0002_rental_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='returned',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='what',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='when',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='who',
        ),
        migrations.AddField(
            model_name='rental',
            name='whoo',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='rental',
            name='name',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
