# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0005_rental_whoo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='whoo',
        ),
    ]
