# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0011_auto_20170329_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='who',
        ),
    ]
